# Yarn v4 configuration for happy-vue monorepo

# Use node_modules linker for NativeScript compatibility
# (NativeScript doesn't support Yarn PnP)
nodeLinker: node-modules

# Enable compression for better cache performance
compressionLevel: mixed

# Prefer deferred versioning for cleaner installs
preferDeferredVersions: true

# Enable workspaces
enableGlobalCache: true
